channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - mpi4py=3.0.3
  - tensorflow-gpu=1.15.0
  - pip
  - matplotlib
  - seaborn
  - joblib
  - pip:
    - gym==0.15.4
    - procgen==0.9.2
    - pytest # for baselines
